export const UPDATE_USER = "UPDATE_USER";
export const SING_OUT = "SING_OUT";
export const FAVOURITE_ADD_PRODUCT = "FAVOURITE_ADD_PRODUCT";
export const FAVORITE_REMOVE_PRODUCT = "FAVORITE_REMOVE_PRODUCT";
